version: '2.2'
services:
  wintercms:
    image: hiltonbanes/wintercms:php7.4-apache
    ports:
      - 8888:80
    volumes:
      - .:/var/www/html/plugins/mikp/s3browser/
    environment:
      - APP_DEBUG=true
      - COMPOSER_UPDATE=true
      - INIT_WINTER=true
      - CMS_ADMIN_PASSWORD=admin
