version: '2.2'
services:
  wintercms:
    image: hiltonbanes/wintercms:php7.4-apache
    ports:
      - 8888:80
    volumes:
      - .:/var/www/html/plugins/mikp/s3browser/
    environment:
      - APP_DEBUG=true
      - COMPOSER_UPDATE=true
      - INIT_WINTER=true
      - PHP_MEMORY_LIMIT=8192M
      - PHP_UPLOAD_MAX_FILESIZE=5G
      - PHP_POST_MAX_SIZE=5G
      - CACHE_STORE=redis
      - DB_REDIS_HOST=redis
      - CMS_ADMIN_PASSWORD=admin

  redis:
    image: redis:latest
